[package]
name = "rust-dno-crawler"
version = "0.0.1"
edition = "2024"

[workspace]
resolver = "2"
members = [
    "./",
    "src/api",
    "src/auth",
    "src/core",
    "src/website"
]

[workspace.package]
version = "0.0.1"

[dependencies]
# Add your workspace crates here
api = { path = "src/api" }
auth = { path = "src/auth" }
core = { path = "src/core" }
website = { path = "src/website" }

# Direct dependencies
anyhow = { workspace = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros", "full"] }
dioxus = { workspace = true }

[workspace.dependencies]
anyhow = { version = "1.0.97" }
serde_json = { version = "1.0.140" }
tokio = { version = "1.45.0" }
reqwest = { version = "0.12.15" }
scraper = { version = "0.23.1" }
serde = { version = "1.0.219" }
spider = { version = "2.37.52", default-features = false }

dioxus = { version = "0.6.2" }

sqlx = { version = "0.7.0" }

axum_session = { version = "0.12.1" }
axum_session_auth = { version = "0.12.1" }
axum = { version = "0.7.0" }

bcrypt = { version = "0.17.0" }
async-trait = { version = "0.1.87" }


[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"

[profile.release]
opt-level = "z"
debug = false
lto = true
codegen-units = 1
panic = "abort"
strip = true
incremental = false
