[package]
name = "rust-dno-crawler"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.98" }
serde_json = { version = "1.0.140" }        
tokio = { version = "1.45.0", features = ["full"] }
reqwest = { version = "0.12.15" }
scraper = { version = "0.23.1" }            
serde = { version = "1.0.219", features = ["derive"] }
spider = { version = "2.37.52", default-features = false } 

dioxus = { version = "0.6.3", features = ["router"] }
dioxus-ssr = { version = "0.6.2" }                      

sqlx = { version = "0.7.4", features = ["sqlite", "runtime-tokio-native-tls", "macros", "chrono", "uuid"] } 

axum_session = { version = "0.12.4" }
axum_session_auth = { version = "0.12.1" } 
axum = { version = "0.7.9" }             

bcrypt = { version = "0.17.0" }          
async-trait = { version = "0.1.87" }     

tower = "0.5.2"
tower-http = { version = "0.5.2", features = ["cors", "fs"] } 

jsonwebtoken = "9.0.0"
chrono = { version = "0.4.41", features = ["serde"] }
uuid = { version = "1.0.3", features = ["v4", "serde"] }
thiserror = "2.0.12"                    
regex = "1.9.6"

tracing = "0.1.38"
tracing-subscriber = "0.3.17"
dotenv = "0.15.0"

[dev-dependencies]
tokio-test = "0.4.4"

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"

[profile.release]
opt-level = "z"
debug = false
lto = true
codegen-units = 1
panic = "abort"
strip = true
incremental = false


