[package]
name = "rust-dno-crawler"
version = "0.0.1"
edition = "2024"

[workspace]
resolver = "2"
members = [
    "./",
    "./api",
    "./core",
    "./website"
]

[workspace.package]
version = "0.0.1"

[dependencies]
# Add your workspace crates here
api = { workspace = true }
core = { workspace = true }
website = { workspace = true }

# Direct dependencies
anyhow = { workspace = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros", "full"] }

[workspace.dependencies]
api = { path = "./api" }
core = { path = "./core" }
website = { path = "./website" }

anyhow = { version = "1.0.97" }
serde_json = { version = "1.0.140" }
tokio = { version = "1.45.0" }
reqwest = { version = "0.12.15" }
scraper = { version = "0.23.1" }
serde = { version = "1.0.219" }
spider = { version = "2.37.52", default-features = false }

dioxus = { version = "0.6.2" }

sqlx = { version = "0.7.0" }

axum_session = { version = "0.12.1" }
axum_session_auth = { version = "0.12.1" }
axum = { version = "0.7.0" }

bcrypt = { version = "0.17.0" }
async-trait = { version = "0.1.87" }

tower = "0.4"
tower-http = { version = "0.5", features = ["cors"] }
jsonwebtoken = "9.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
thiserror = "1.0"
regex = "1.0"

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"

[profile.release]
opt-level = "z"
debug = false
lto = true
codegen-units = 1
panic = "abort"
strip = true
incremental = false
