[application]
name = "rust-dno-crawler-website"
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

[web.app]
# HTML title tag content
title = "DNO Crawler - Development"
# base_path = "" # Re-add or adjust if you need a non-root base path for your app's URLs

[web.watcher]
# when watcher trigger, regenerate the `index.html`
reload_html = true
# enable CSS hot-reload
reload_css = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "public", "../tailwind_input.css"]

[web.resource]
# Resource (static asset) configuration
# These sections define where static files are found for dev and prod builds.

[web.resource.dev]
# Resource (public) file folder for development builds
dir = "public"

[web.resource.prod]
# Resource (public) file folder for production builds
dir = "public"

# The proxy configuration now expects an array of proxy rules.
# Each rule is a table within the array.
[[web.proxy]]
# backend server for API calls during development
backend = "http://localhost:3000/api" # <--- CHANGED: Added trailing slash

[build]
# development optimizations
default_platform = "web"